apiVersion: v1
kind: PersistentVolume
metadata: 
  name: nfs001-pv
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  mountOptions:
    - hard
  nfs:
    path: /share
    server: 192.168.5.212